name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  validate_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Inatall Dependecncy
        run: npm ci
      - name: Install Allure
        run: npm install allure-commandline -g
      - name: Execute allure command
        run: allure -h
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
